
service: sns-test

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MY_VAR: MY_VAL

functions:
  pong:
    handler: pong.pong
    events:
      - sns:
         topicName: test-topic
  ping:
    handler: ping.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
plugins:
  - serverless-offline-sns
  - serverless-offline
custom:
  serverless-offline-sns:
    port: 4002
    debug: true 
